# Common configuration for all environments
spring:
  application:
    name: payment-reconciliation
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    "[com.example.paymentreconciliation]": INFO

file:
  upload:
    base-dir: uploads/