# Development environment configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentreconciliation_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    "[com.example.paymentreconciliation]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

file:
  upload:
    base-dir: /Users/rahulcharvekar/Documents/Repos/ManpowerManagement/PaymentReconciliation/uploads/dev/

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics,loggers

# Auditing toggle
auditing:
  enabled: true
