# Production environment configuration for Azure Container Apps
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/paymentreconciliation_prod?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:produser}
    password: ${DB_PASSWORD:prodpassword}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate  # Don't auto-create tables in prod
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": false
        jdbc:
          "[batch_size]": 25
        "[order_inserts]": true
        "[order_updates]": true
        connection:
          "[provider_disables_autocommit]": true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    "[com.example.paymentreconciliation]": INFO
    "[org.hibernate.SQL]": WARN
    "[org.springframework.web]": WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: ${LOG_FILE:/app/logs/payment-reconciliation.log}
    max-size: 100MB
    max-history: 30

file:
  upload:
    base-dir: ${FILE_UPLOAD_DIR:/app/uploads}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
